[env:m5dial]
platform = espressif32@6.9.0
board = m5stack-stamps3
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = partitions_ota_8mb.csv
board_build.f_cpu = 240000000L
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DBOARD_HAS_PSRAM=0
    -DFW_VERSION='"0.2.0"'
build_src_filter = +<*> +<buddies/>
lib_deps =
    m5stack/M5Dial @ ^1.0.3
    bitbank2/AnimatedGIF @ ^2.1.1
    bblanchon/ArduinoJson @ ^7.0.0
